### ISSUE TITLE
Error in python 3.5 after downloading database

### ISSUE THREAD

**Issue by skeevey** [Tenchi2xh/pokedex-cli#10]
```
Downloading Veekun Pokédex database...
100% (15778973 of 15778973) |###########################| Elapsed Time: 0:00:00 Time: 0:00:00
Traceback (most recent call last):
  File "/usr/local/bin/pokedex", line 9, in <module>
    load_entry_point('pokedex-cli==0.1.4', 'console_scripts', 'pokedex')()
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pokedex/main.py", line 27, in pokedex
    download_database()
  File "/usr/local/lib/python3.5/dist-packages/pokedex/database/get.py", line 27, in download_database
    gzipped += chunk
TypeError: Can't convert 'bytes' object to str implicitly
```

**Comment by Tenchi2xh** [comment]
For now pokedex-cli is not compatible with Python 3.
@tommyp1ckles has a [branch](https://github.com/tommyp1ckles/pokedex-cli) which fixes the incompatibilities, I will test it and merge it when I have the time.

For now, either try the branch or use Python 2! :)

**Comment by zJairO** [comment]
Same issue rn, it doesn't work with python 3.

**Comment by LautiLosio** [comment]
The branch mentioned on the reply from 2016 is not working either.
I managed to fix this myself with help of ChatGPT and i will be creating a pull request.
I hope the author sees this!

**Comment by cdkw2** [comment]
> The branch mentioned on the reply from 2016 is not working either. I managed to fix this myself with help of ChatGPT and i will be creating a pull request. I hope the author sees this!

What about the pull request?

**Comment by Rajveer-2009** [comment]
Anyone wandering how to install pokedex-cli in python3:

```
$ git clone https://github.com/LautiLosio/pokedex-cli.git
$ cd pokedex-cli
$ python3 setup.py install
```

**Comment by cdkw2** [comment]
> Anyone wandering how to install pokedex-cli in python3:
> 
> ```
> $ git clone https://github.com/LautiLosio/pokedex-cli.git
> $ cd pokedex-cli
> $ python3 setup.py install
> ```

thanks!

**Comment by LautiLosio** [comment]
PR #11 got merged last year.
