### ISSUE TITLE
TypeError on OS X

### ISSUE THREAD

**Issue by frdmn** [Tenchi2xh/pokedex-cli#7]
Version information:
- Python 2.7.12
- pokedex-cli 0.1.4

Error:

```
❯  ~  pokedex 1
Downloading Veekun Pokédex database...
Traceback (most recent call last):
  File "/usr/local/bin/pokedex", line 9, in <module>
    load_entry_point('pokedex-cli==0.1.4', 'console_scripts', 'pokedex')()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pokedex/main.py", line 27, in pokedex
    download_database()
  File "/usr/local/lib/python2.7/site-packages/pokedex/database/get.py", line 24, in download_database
    with ProgressBar(max_value=total_length) as bar:
TypeError: __init__() got an unexpected keyword argument 'max_value'
```

**Comment by Tenchi2xh** [comment]
What version of `progressbar2` do you have? (`pip show progressbar2`)
You might need to `pip install` with `-U` to force upgrading the modules you already have

**Comment by frdmn** [comment]
Here's the output:

```
Metadata-Version: 2.0
Name: progressbar2
Version: 2.7.3
Summary: Text progress bar library for Python.
Home-page: https://github.com/WoLpH/python-progressbar
Author: Rick van Hattem
Author-email: Rick.van.Hattem@Fawo.nl
Installer: pip
License: LICENSE.txt
Location: /usr/local/lib/python2.7/site-packages
Requires:
Classifiers:
  Development Status :: 5 - Production/Stable
  Environment :: Console
  Intended Audience :: Developers
  Intended Audience :: Information Technology
  Intended Audience :: System Administrators
  License :: OSI Approved :: GNU Library or Lesser General Public License (LGPL)
  License :: OSI Approved :: BSD License
  Operating System :: OS Independent
  Programming Language :: Python
  Programming Language :: Python :: 2
  Programming Language :: Python :: 2.4
  Programming Language :: Python :: 2.5
  Programming Language :: Python :: 2.6
  Programming Language :: Python :: 2.7
  Programming Language :: Python :: 3
  Topic :: Software Development :: Libraries
  Topic :: Software Development :: User Interfaces
  Topic :: Terminals
```

Works fine after upgrading to version `2.3` using `pip install -U progressbar2`.

Thanks, @Tenchi2xh!
